//! Contains the app controller

use std::cell::Cell;
use std::path::PathBuf;
use std::time::Instant;

use derive_more::Display;
use iced::advanced::{Layout, Widget, layout, mouse, renderer, widget};
use iced::{Event, Rectangle};
use iced_wgpu::core::SmolStr;
use iced_wgpu::{Renderer, wgpu};
use iced_widget::{button, column, combo_box, container, row, text};
use iced_winit::conversion::cursor_position;
use iced_winit::core::{Color, Element, Theme};
use iced_winit::winit::dpi::{LogicalInsets, LogicalSize, PhysicalInsets, PhysicalPosition};
use iced_winit::winit::event::{ElementState, MouseButton};
use iced_winit::winit::keyboard::ModifiersState;
use nalgebra as na;

use crate::controls::coords::{LocalCoords, Physical};
use crate::hello_triangle::HelloWidget;
use crate::image::{ClampedSplit, Image, ImageMessage, ImageWidget, SplitReaction};
use crate::instruments::pipeline::passthru::PassThruPipeline;
use crate::instruments::{GpuContext, TargetContext};
use crate::physics::{PhysicsMessage, PhysicsWidget};
use crate::viewport::{ViewportGui, ViewportMessage};

pub mod coords;

/// The high-level message of the app generated by user input
#[derive(Debug, Clone)]
pub enum Message {
    /// Update the scale factor
    SetScaleFactor(f32),
    /// Switch the displayed scene
    SwitchScene(Scene),
    /// Open the file picker
    SelectFile,
    /// Mouse scrolled up
    ScrollUp,
    /// Mouse scrolled down
    ScrollDown,
    /// The cursor moved to a new position
    CursorMoved(Physical<na::Point2<f32>>),
    /// A mouse button was pressed
    MouseInput {
        /// The button pressed
        button: MouseButton,
        /// If pressed or released
        state: ElementState,
    },
    /// Modifier key was pressed
    ModifiersChanged(ModifiersState),
    /// A keyboard button was pressed
    KeyPress(SmolStr),
    /// Poll as requested
    Poll,
    /// A message intended for the image widget
    Image(ImageMessage),
    /// A message intended for the physics widget
    Physics(PhysicsMessage),
}

/// Response by the controller to the app executor
#[derive(Debug, Default)]
#[must_use]
pub enum Response {
    /// Nothing changed, keep as is
    #[default]
    NoChange,
    /// Request to close the app
    Exit,
    /// Change how the often we need to update
    Updates(Updates),
}

/// Describes when we need updates to happen
#[derive(Debug)]
pub enum Updates {
    /// Only update when some event was triggered
    OnEvent,
    /// Request an update to the provided instant at the latest
    NextTime(Instant),
}

/// Struct controlling what is displayed by the app
///
/// This is also where user input is handled.
pub struct Controls {
    /// Bounds in a cell so that we can update its value with the computed layout from iced by
    /// passing a reference to the widget's draw call. The layout system gives us logical
    /// coordinates, so store them as such.
    scene_bounds: Cell<Option<PhysicalInsets<u32>>>,
    /// The viewport of the wgpu area
    viewport: ViewportGui,
    /// A general-purpose pass-thru pipeline
    passthru: PassThruPipeline,
    /// The current scene to display
    scene: CurrentScene,

    /// Combo box state for scene selection
    combo_box_scene: combo_box::State<Scene>,
    /// The state of the left mouse button
    mouse_button: ElementState,
    /// The location of the cursor
    cursor: CursorState,
    /// The state of the modifier keys on the keyboard
    modifiers: ModifiersState,
}

impl Controls {
    /// Fixed (logical) size of the control panel
    const PANEL_WIDTH: u32 = 150;
    /// Minimal (logical) size of the render viewport
    const MIN_VIEW_SIZE: u32 = 200;

    /// Create a new controller
    pub fn new(ctx: &GpuContext, target: &TargetContext) -> Self {
        let scene_bounds = Cell::new(None);
        let viewport = ViewportGui::new();
        let passthru = PassThruPipeline::new(ctx, target.config.format);
        let scene = CurrentScene::triangle(ctx, target);

        let combo_box_scene =
            combo_box::State::new(vec![Scene::HelloTriangle, Scene::Image, Scene::Physics]);
        let mouse_button = ElementState::Released;
        let cursor = CursorState::default();
        let modifiers = ModifiersState::default();
        Self {
            scene_bounds,
            viewport,
            passthru,
            scene,

            combo_box_scene,
            mouse_button,
            cursor,
            modifiers,
        }
    }

    /// Create the Iced view of the gui
    pub fn view(&self, scale_factor: f32) -> Element<'_, Message, Theme, Renderer> {
        use iced::Length::Fill;

        self.scene_bounds.set(None);

        let bg_color = match &self.scene {
            CurrentScene::HelloTriangle(_) => HelloWidget::bg_color(),
            CurrentScene::Image(_) => Color::BLACK,
            CurrentScene::Physics(_) => Color::BLACK,
        };

        let bounds = &self.scene_bounds;
        let split = match &self.scene {
            CurrentScene::HelloTriangle(_) => None,
            CurrentScene::Image(image) => image.split(),
            CurrentScene::Physics(_) => None,
        };
        let placeholder = PlaceholderWidget {
            bounds,
            split,
            bg_color,
            scale_factor,
        };
        let scene = Element::new(placeholder);

        let current_scene = match self.scene {
            CurrentScene::HelloTriangle(_) => Scene::HelloTriangle,
            CurrentScene::Image(_) => Scene::Image,
            CurrentScene::Physics(_) => Scene::Physics,
        };
        // combo_box(state, placeholder, selection, on_selected)
        let control = column![
            container(
                text("Graphics Playground")
                    .style(text::base)
                    .center()
                    .width(Fill)
            )
            .align_top(60.),
            combo_box(
                &self.combo_box_scene,
                "Select scene...",
                Some(&current_scene),
                Message::SwitchScene,
            )
            .width(Fill),
        ]
        .width(Self::PANEL_WIDTH as f32)
        .padding(5);

        let control = match &self.scene {
            CurrentScene::HelloTriangle(_) => control,
            CurrentScene::Image(_) => control
                .push(iced::widget::space().height(5.))
                .push(
                    button(text("Open Image").center().width(Fill))
                        .width(Fill)
                        .on_press(Message::SelectFile),
                )
                .push(
                    button(text("Toggle Filter").center().width(Fill))
                        .padding(5.)
                        .width(Fill)
                        .on_press(Message::Image(ImageMessage::CycleFilters)),
                )
                .push(
                    button(text("Reset Pos").center().width(Fill))
                        .width(Fill)
                        .on_press(Message::Image(ImageMessage::ResetPosition)),
                )
                .push(
                    button(text("Reset Zoom").center().width(Fill))
                        .width(Fill)
                        .on_press(Message::Image(ImageMessage::Viewport(
                            ViewportMessage::SetZoom {
                                fix_point: na::Point2::origin(),
                                zoom: 1.,
                            },
                        ))),
                ),
            CurrentScene::Physics(_) => control.push(
                button(text("Reset").center().width(Fill))
                    .width(Fill)
                    .on_press(Message::Physics(PhysicsMessage::Reset)),
            ),
        };

        row![control, scene].into()
    }

    /// Handle an application-specific event
    ///
    /// TODO: Returns [`std::ops::ControlFlow`] because this can be short-curcuited with `?` try
    /// operator. Replace with a custom type when the `Try` trait is stabilized:
    /// <https://github.com/rust-lang/rust/issues/84277>
    pub fn update(
        &mut self,
        ctx: &GpuContext,
        target: &TargetContext,
        message: Message,
    ) -> Response {
        match (&mut self.scene, message) {
            (current, Message::SwitchScene(next)) if &next != current => match next {
                Scene::HelloTriangle => {
                    self.scene = CurrentScene::triangle(ctx, target);
                    return Response::Updates(Updates::OnEvent);
                }
                Scene::Image => {
                    self.scene = CurrentScene::image();
                    return Response::Updates(Updates::OnEvent);
                }
                Scene::Physics => {
                    let (scene, next) = CurrentScene::physics(ctx, target);
                    self.scene = scene;
                    return Response::Updates(Updates::NextTime(next));
                }
            },
            (_, Message::SwitchScene(_)) => (),

            (_, Message::SetScaleFactor(factor)) => self.viewport.update_scale_factor(factor),
            (_, Message::ModifiersChanged(mods)) => self.modifiers = mods,
            (_, Message::CursorMoved(position)) => self.cursor_moved(position),
            (_, Message::ScrollUp) => self.scroll_up(),
            (_, Message::ScrollDown) => self.scroll_down(),
            (_, Message::MouseInput { button, state }) => self.mouse_input(button, state),
            (_, Message::KeyPress(key)) => return self.key_pressed(&key),
            (_, Message::Poll) => return self.got_polled(),

            (CurrentScene::HelloTriangle(_), Message::SelectFile) => (),

            (CurrentScene::Image(widget), Message::SelectFile) => {
                let image = Self::pick_image_dialog().and_then(|path| {
                    Image::load(&path)
                        .inspect_err(|e| eprintln!("Could not load image: {e}"))
                        .ok()
                });
                if let Some(image) = image {
                    let msg = ImageMessage::SetImage(image);
                    widget.update(msg);
                }
            }
            (CurrentScene::Image(widget), Message::Image(msg)) => widget.update(msg),
            (_, Message::Image(..)) => (),
            (CurrentScene::Physics(widget), Message::Physics(msg)) => widget.update(msg),
            (CurrentScene::Physics(_), _) => (),
            (_, Message::Physics(_)) => (),
        }
        Response::NoChange
    }

    /// Get the window minimal size constraints
    pub const fn min_window_size() -> LogicalSize<u32> {
        LogicalSize {
            width: Self::MIN_VIEW_SIZE + Self::PANEL_WIDTH,
            height: Self::MIN_VIEW_SIZE,
        }
    }

    /// Get the current keyboard modifiers
    pub const fn modifiers(&self) -> ModifiersState {
        self.modifiers
    }

    /// Get the current cursor for Iced
    pub fn cursor(&self) -> iced::mouse::Cursor {
        let Some(Physical(pos)) = self.cursor.pos() else {
            return iced::mouse::Cursor::Unavailable;
        };
        let pos = PhysicalPosition { x: pos.x, y: pos.y }.cast();
        let scale = self.viewport.coords().scale_factor();
        let cursor = cursor_position(pos, scale);
        iced::mouse::Cursor::Available(cursor)
    }

    /// Must be called after [`Controls::view`] to know the viewport bounds.
    pub fn draw_wgpu(
        &mut self,
        ctx: &GpuContext,
        target: &TargetContext,
        view: &wgpu::TextureView,
    ) {
        let Some(bounds) = self.scene_bounds.take() else {
            eprintln!("TRIED TO DRAW WITH NO SCENE BOUNDS!");
            return;
        };

        self.viewport.update_bounds(bounds);

        let mut encoder = ctx
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Frame Draw Command Encoder"),
            });

        let context = &mut RenderContext {
            ctx,
            target,
            passthru: &self.passthru,
            encoder: &mut encoder,
            viewport: &self.viewport,
        };

        let output = match &mut self.scene {
            CurrentScene::HelloTriangle(scene) => scene.render(context),
            CurrentScene::Image(scene) => scene.render(context),
            CurrentScene::Physics(scene) => scene.render(context),
        };

        let Some(output) = output else {
            return;
        };

        self.viewport
            .draw(&self.passthru, &mut encoder, output, view);

        ctx.queue.submit([encoder.finish()]);
    }

    /// Let the user select an image file
    fn pick_image_dialog() -> Option<PathBuf> {
        rfd::FileDialog::new()
            .set_title("Pick image to display")
            .add_filter("image", &["jpg", "jpeg", "png", "avif", "webp", "jxl"])
            .pick_file()
    }

    /// Handle a keyboard button press
    fn key_pressed(&mut self, key: &SmolStr) -> Response {
        // Quit with CTRL+Q
        if key.as_str() == "q" && self.modifiers.control_key() {
            return Response::Exit;
        }

        match &mut self.scene {
            CurrentScene::HelloTriangle(_) => (),
            CurrentScene::Image(widget) => {
                if let Some(pos) = self.cursor.pos()
                    && let pos = self.viewport.coords().local_point(pos)
                    && let Some(message) = ImageMessage::from_key(key, pos)
                {
                    widget.update(message);
                }
            }
            CurrentScene::Physics(_) => (),
        }
        Response::NoChange
    }

    /// Handle the moved cursor
    fn cursor_moved(&mut self, position: Physical<na::Point2<f32>>) {
        let cursor = CursorState::LastPos(position);
        let last = std::mem::replace(&mut self.cursor, cursor);

        let Some(last) = last.pos() else {
            return;
        };

        let offset = Physical(position.0 - last.0);
        let offset = self.viewport.coords().local_vector(offset);

        match &mut self.scene {
            CurrentScene::HelloTriangle(_) => (),

            CurrentScene::Image(widget) if self.mouse_button == ElementState::Pressed => {
                let message = ViewportMessage::Pan(offset);
                let message = ImageMessage::Viewport(message);
                widget.update(message);
            }
            CurrentScene::Image(_) => (),

            CurrentScene::Physics(widget) if self.mouse_button == ElementState::Pressed => {
                let message = ViewportMessage::Pan(offset);
                let message = PhysicsMessage::Viewport(message);
                widget.update(message);
            }
            CurrentScene::Physics(_) => (),
        }
    }

    /// Handle mouse scrolling up
    fn scroll_up(&mut self) {
        let cursor = self
            .cursor
            .pos()
            .and_then(|cursor| self.viewport.coords().local_point(cursor))
            .unwrap_or_default();
        let message = ViewportMessage::zoom_in(cursor);

        match &mut self.scene {
            CurrentScene::HelloTriangle(_) => (),
            CurrentScene::Image(widget) => {
                let message = ImageMessage::Viewport(message);
                widget.update(message);
            }
            CurrentScene::Physics(widget) => {
                let message = PhysicsMessage::Viewport(message);
                widget.update(message);
            }
        }
    }

    /// Handle mouse scrolling up
    fn scroll_down(&mut self) {
        let cursor = self
            .cursor
            .pos()
            .and_then(|cursor| self.viewport.coords().local_point(cursor))
            .unwrap_or_default();
        let message = ViewportMessage::zoom_out(cursor);

        match &mut self.scene {
            CurrentScene::HelloTriangle(_) => (),
            CurrentScene::Image(widget) => {
                let message = ImageMessage::Viewport(message);
                widget.update(message);
            }
            CurrentScene::Physics(widget) => {
                let message = PhysicsMessage::Viewport(message);
                widget.update(message);
            }
        }
    }

    /// Handle a mouse button pressed
    fn mouse_input(&mut self, button: MouseButton, state: ElementState) {
        let MouseButton::Left = button else {
            return;
        };
        match state {
            ElementState::Pressed => {
                if let Some(pos) = self.cursor.pos()
                    && self.viewport.coords().local_point(pos).is_some()
                {
                    self.mouse_button = state;
                }
            }
            ElementState::Released => self.mouse_button = ElementState::Released,
        }
        match &mut self.scene {
            CurrentScene::HelloTriangle(_) => (),
            CurrentScene::Image(widget) => {
                let active = self.mouse_button == ElementState::Pressed;
                let message = ImageMessage::Panning { active };
                widget.update(message);
            }
            CurrentScene::Physics(_) => (),
        }
    }

    /// React to the poll signal from the application
    fn got_polled(&mut self) -> Response {
        let updates = match &mut self.scene {
            CurrentScene::HelloTriangle(_) => Updates::OnEvent,
            CurrentScene::Image(_) => Updates::OnEvent,
            CurrentScene::Physics(widget) => {
                let next = widget.tick();
                Updates::NextTime(next)
            }
        };
        Response::Updates(updates)
    }
}

/// Determines which scene is currently displayed by the GUI
#[expect(clippy::large_enum_variant)]
enum CurrentScene {
    /// Display the Hello World triangle
    HelloTriangle(HelloWidget),
    /// Display the image viewer widget
    Image(ImageWidget),
    /// Display the 2d physics widget
    Physics(PhysicsWidget),
}

impl CurrentScene {
    /// Constructor for [`Self::HelloTriangle`]
    fn triangle(ctx: &GpuContext, target: &TargetContext) -> Self {
        let scene = HelloWidget::new(ctx, target);
        Self::HelloTriangle(scene)
    }

    /// Constructor for [`Self::Image`]
    fn image() -> Self {
        let widget = ImageWidget::new();
        Self::Image(widget)
    }

    /// Constructor for [`Self::Physics`]
    fn physics(ctx: &GpuContext, target: &TargetContext) -> (Self, Instant) {
        let mut physics = PhysicsWidget::new(ctx, target);
        let next = physics.tick();
        (Self::Physics(physics), next)
    }
}

/// The options of scenes to display in the viewport
#[derive(Debug, Clone, Copy, Display, PartialEq, Eq)]
pub enum Scene {
    /// The [`CurrentScene::HelloTriangle`] scene
    HelloTriangle,
    /// The [`CurrentScene::Image`] scene
    Image,
    /// The [`CurrentScene::Physics`] scene
    Physics,
}

impl PartialEq<CurrentScene> for Scene {
    fn eq(&self, other: &CurrentScene) -> bool {
        matches!(
            (self, other),
            (Self::HelloTriangle, CurrentScene::HelloTriangle(_))
                | (Self::Image, CurrentScene::Image(_))
        )
    }
}

/// A placeholder widget to be used with the Iced layout system
///
/// As iced creates the GUI, the space allocated to this placeholder is instead overdrawn with calls
/// to wgpu directly.
#[derive(Debug, Clone)]
pub struct PlaceholderWidget<'a> {
    /// The current layout bounds get stored here
    bounds: &'a Cell<Option<PhysicalInsets<u32>>>,
    /// The split location
    split: Option<SplitReaction>,
    /// The background color to draw
    bg_color: Color,
    /// The current scale factor
    scale_factor: f32,
}

impl<Theme, Renderer> Widget<Message, Theme, Renderer> for PlaceholderWidget<'_>
where
    Renderer: renderer::Renderer,
{
    fn size(&self) -> iced::Size<iced::Length> {
        iced::Size::new(iced::Length::Fill, iced::Length::Fill)
    }

    fn update(
        &mut self,
        _tree: &mut widget::Tree,
        event: &Event,
        layout: Layout<'_>,
        cursor: mouse::Cursor,
        _renderer: &Renderer,
        _clipboard: &mut dyn iced::advanced::Clipboard,
        shell: &mut iced::advanced::Shell<'_, Message>,
        _viewport: &Rectangle,
    ) {
        if shell.is_event_captured() {
            return;
        }

        let Some(rect) = self.split_rect(layout) else {
            return;
        };

        match event {
            Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) => {
                let Some(local) = self.local_cursor(layout, cursor) else {
                    return;
                };

                // TODO: use other types here, iced types should only be consumed
                let local = iced::Point {
                    x: local.x,
                    y: local.y,
                };
                let inside = rect.contains(local);
                if !inside {
                    return;
                }
                shell.capture_event();
                shell.publish(Message::Image(ImageMessage::DragSplit { active: true }));
            }
            Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)) => {
                shell.publish(Message::Image(ImageMessage::DragSplit { active: false }));
            }
            Event::Keyboard(_)
            | Event::Mouse(_)
            | Event::Window(_)
            | Event::Touch(_)
            | Event::InputMethod(_) => (),
        }
    }

    fn layout(
        &mut self,
        _tree: &mut widget::Tree,
        _renderer: &Renderer,
        limits: &layout::Limits,
    ) -> layout::Node {
        layout::Node::new(limits.max())
    }

    fn draw(
        &self,
        _tree: &widget::Tree,
        renderer: &mut Renderer,
        _theme: &Theme,
        _style: &renderer::Style,
        layout: Layout<'_>,
        _cursor: mouse::Cursor,
        _viewport: &iced::Rectangle,
    ) {
        // Update bounds through the cell
        let bounds = self.compute_bounds(layout);
        self.bounds.set(Some(bounds));

        // Draw the background
        renderer.fill_quad(
            renderer::Quad {
                bounds: layout.bounds(),
                ..Default::default()
            },
            self.bg_color,
        );
    }

    fn mouse_interaction(
        &self,
        _tree: &widget::Tree,
        layout: Layout<'_>,
        cursor: mouse::Cursor,
        _viewport: &Rectangle,
        _renderer: &Renderer,
    ) -> mouse::Interaction {
        let reaction = matches!(self.split, Some(SplitReaction { react: true, .. }));
        if !reaction {
            return mouse::Interaction::None;
        }

        let Some(local) = self.local_cursor(layout, cursor) else {
            return mouse::Interaction::None;
        };
        let Some(rect) = self.split_rect(layout) else {
            return mouse::Interaction::None;
        };

        let local = iced::Point {
            x: local.x,
            y: local.y,
        };
        let inside = rect.contains(local);
        if !inside {
            return mouse::Interaction::None;
        }
        mouse::Interaction::Pointer
    }
}

impl PlaceholderWidget<'_> {
    /// Fixed (physical) width of the split rectangle (for selection)
    const SPLIT_WIDTH: f32 = 20.;

    /// Get the bounds in pixels available to us
    fn compute_bounds(&self, layout: Layout<'_>) -> PhysicalInsets<u32> {
        let bounds = layout.bounds();
        let inset = LogicalInsets {
            top: bounds.y,
            left: bounds.x,
            bottom: bounds.y + bounds.height,
            right: bounds.x + bounds.width,
        };
        inset.to_physical(self.scale_factor as f64)
    }

    /// Get the rectangle where the image splitter is selectable
    fn split_rect(&self, layout: Layout<'_>) -> Option<Rectangle<f32>> {
        let bounds = self.compute_bounds(layout);
        let coords = LocalCoords::new(bounds, self.scale_factor);
        let half = coords.size().width as f32 / 2.;
        let x = match self.split?.split {
            ClampedSplit::FullLeft => -half,
            ClampedSplit::Split(pos) => pos,
            ClampedSplit::FullRight => half,
        };

        Some(Rectangle {
            x: x - Self::SPLIT_WIDTH / 2.,
            y: -(coords.size().height as f32 / 2.),
            width: Self::SPLIT_WIDTH,
            height: coords.size().height as f32,
        })
    }

    /// Get the position of the cursor within the current viewport area
    fn local_cursor(
        &self,
        layout: Layout<'_>,
        cursor: iced::mouse::Cursor,
    ) -> Option<na::Point2<f32>> {
        let iced::Point { x, y } = cursor.position()?;
        let point = Physical(na::Point2::new(x, y));

        let bounds = self.compute_bounds(layout);
        let coords = LocalCoords::new(bounds, self.scale_factor);
        coords.local_point(point)
    }
}

/// Tracks the cursor within the window
#[derive(Debug, Clone, Copy, Default)]
pub enum CursorState {
    /// No position known
    #[default]
    Unknown,
    /// Got the position of the cursor
    LastPos(Physical<na::Point2<f32>>),
}

impl CursorState {
    /// Get the current position of the cursor
    const fn pos(self) -> Option<Physical<na::Point2<f32>>> {
        match self {
            Self::Unknown => None,
            Self::LastPos(pos) => Some(pos),
        }
    }
}

/// References to all data structures needed for widgets to render their scene
#[non_exhaustive]
pub struct RenderContext<'a> {
    /// The device and queue
    pub ctx: &'a GpuContext,
    /// Context about the window and its surface
    pub target: &'a TargetContext,
    /// The passthru pipeline to render to the viewport
    pub passthru: &'a PassThruPipeline,
    /// The command encoder for the current frame
    pub encoder: &'a mut wgpu::CommandEncoder,
    /// The viewport to which the render output should contain itself
    pub viewport: &'a ViewportGui,
}
